// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzfaxEAzVpNTIc7KI5rc4iuvk00HwdAeA',
    appId: '1:14081653340:web:0164dea996e7c72ffbc499',
    messagingSenderId: '14081653340',
    projectId: 'task-reminder-app-2d1fa',
    authDomain: 'task-reminder-app-2d1fa.firebaseapp.com',
    storageBucket: 'task-reminder-app-2d1fa.firebasestorage.app',
    measurementId: 'G-ZJPPWVMHTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMi8mx77lssN7sMT6-SDjy7MkReh5u5us',
    appId: '1:14081653340:android:290e5241c3b84b41fbc499',
    messagingSenderId: '14081653340',
    projectId: 'task-reminder-app-2d1fa',
    storageBucket: 'task-reminder-app-2d1fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVyNTpvp8Jv3B56w7V0BfrKjSsJ9HSi_g',
    appId: '1:14081653340:ios:32b01685dfcaf526fbc499',
    messagingSenderId: '14081653340',
    projectId: 'task-reminder-app-2d1fa',
    storageBucket: 'task-reminder-app-2d1fa.firebasestorage.app',
    iosBundleId: 'com.example.taskReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVyNTpvp8Jv3B56w7V0BfrKjSsJ9HSi_g',
    appId: '1:14081653340:ios:32b01685dfcaf526fbc499',
    messagingSenderId: '14081653340',
    projectId: 'task-reminder-app-2d1fa',
    storageBucket: 'task-reminder-app-2d1fa.firebasestorage.app',
    iosBundleId: 'com.example.taskReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzfaxEAzVpNTIc7KI5rc4iuvk00HwdAeA',
    appId: '1:14081653340:web:06f79ef64455be89fbc499',
    messagingSenderId: '14081653340',
    projectId: 'task-reminder-app-2d1fa',
    authDomain: 'task-reminder-app-2d1fa.firebaseapp.com',
    storageBucket: 'task-reminder-app-2d1fa.firebasestorage.app',
    measurementId: 'G-7JCC8BS0QH',
  );
}
